/**
 * Industries directory — 40+ verticals with per-vertical campaign guidance.
 * Feeds /industries hub + dynamic /industries/[slug] detail pages.
 */

export type Industry = {
  slug: string;
  name: string;
  cluster: ClusterId;
  oneLine: string; // short positioning line for hub/featured cards
  typicalOffer: string;
  routeMix: string;
  timing: string;
  recommendedProducts: string[]; // slugs from lib/products.ts
  relatedIndustries: string[]; // slugs
};

export type ClusterId =
  | "home-services"
  | "medical-wellness"
  | "food-hospitality"
  | "fitness-education"
  | "retail-trade-pro"
  | "professional-financial";

export const CLUSTERS: {
  id: ClusterId;
  name: string;
  blurb: string;
}[] = [
  {
    id: "home-services",
    name: "Home services",
    blurb: "Seasonal and demand-driven campaigns — HVAC, plumbing, roofing, electrical, cleaning, pest control, and more.",
  },
  {
    id: "medical-wellness",
    name: "Medical & wellness",
    blurb: "Patient acquisition and retention for dental, medical, chiropractic, med spa, and personal-care practices.",
  },
  {
    id: "food-hospitality",
    name: "Food & hospitality",
    blurb: "Grand openings, seasonal menus, and repeat-visit campaigns for local restaurants, cafes, bars, and pizzerias.",
  },
  {
    id: "fitness-education",
    name: "Fitness & education",
    blurb: "New-year intros, seasonal programs, and community-building for gyms, studios, schools, and tutoring services.",
  },
  {
    id: "retail-trade-pro",
    name: "Retail, trade & service",
    blurb: "Auto, storage, florists, pet services, dry cleaners, movers — trade and retail with a local service footprint.",
  },
  {
    id: "professional-financial",
    name: "Professional & financial",
    blurb: "Reputation-led campaigns for real estate, mortgage, insurance, legal, and accounting practices.",
  },
];

export const INDUSTRIES: Industry[] = [
  // HOME SERVICES
  {
    slug: "hvac",
    name: "HVAC",
    cluster: "home-services",
    oneLine: "Seasonal tune-up campaigns and emergency-demand direct mail for HVAC businesses.",
    typicalOffer: "Seasonal tune-up, free estimate, bundled service packages.",
    routeMix: "Dense residential routes around service area, drive-time filtered.",
    timing: "Drop 2–4 weeks before peak season (spring and fall).",
    recommendedProducts: ["eddm-postcards", "door-hangers", "business-cards"],
    relatedIndustries: ["plumbing", "electrical", "roofing"],
  },
  {
    slug: "plumbing",
    name: "Plumbing",
    cluster: "home-services",
    oneLine: "Emergency-demand and preventive-service campaigns for plumbing businesses.",
    typicalOffer: "Free estimate, drain clean special, 24/7 emergency service.",
    routeMix: "Residential routes within drive time; older-home dense neighborhoods.",
    timing: "Year-round with spring + winter pushes.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "business-cards"],
    relatedIndustries: ["hvac", "electrical", "handyman"],
  },
  {
    slug: "roofing",
    name: "Roofing",
    cluster: "home-services",
    oneLine: "Storm-response and inspection campaigns for roofing businesses.",
    typicalOffer: "Free inspection, storm-response check, roof age estimate.",
    routeMix: "Neighborhoods within recent weather exposure; older-home density.",
    timing: "Rapid deployment after storms; steady year-round inspection offers.",
    recommendedProducts: ["eddm-postcards", "oversized-postcards", "door-hangers"],
    relatedIndustries: ["hvac", "remodeling", "solar"],
  },
  {
    slug: "electrical",
    name: "Electrical",
    cluster: "home-services",
    oneLine: "Panel-upgrade and EV-charger installation campaigns for electricians.",
    typicalOffer: "Free estimate, panel upgrade special, EV charger install.",
    routeMix: "Residential routes with older homes or newer EV-adoption areas.",
    timing: "Year-round with spring + summer pushes.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "business-cards"],
    relatedIndustries: ["plumbing", "hvac", "solar"],
  },
  {
    slug: "landscaping",
    name: "Landscaping",
    cluster: "home-services",
    oneLine: "Seasonal service and maintenance-plan campaigns for landscapers.",
    typicalOffer: "Seasonal cleanup, annual maintenance plans, free design.",
    routeMix: "Residential routes with medium-to-large lots.",
    timing: "Spring kickoff; fall winterization.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "flyers"],
    relatedIndustries: ["pool-service", "pest-control", "cleaning-services"],
  },
  {
    slug: "pest-control",
    name: "Pest control",
    cluster: "home-services",
    oneLine: "Seasonal pest and preventive campaigns for pest-control services.",
    typicalOffer: "Free inspection, seasonal quarterly plans, family-safe treatment.",
    routeMix: "Residential routes; family-heavy neighborhoods.",
    timing: "Spring and fall waves; year-round maintenance.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "business-cards"],
    relatedIndustries: ["landscaping", "cleaning-services", "handyman"],
  },
  {
    slug: "cleaning-services",
    name: "Cleaning services",
    cluster: "home-services",
    oneLine: "Recurring and move-out cleaning campaigns for home cleaners.",
    typicalOffer: "First-cleaning discount, recurring service bundle, move-out special.",
    routeMix: "Dense residential routes; apartment-heavy areas for move-outs.",
    timing: "Monthly cadence works best.",
    recommendedProducts: ["eddm-postcards", "flyers", "business-cards"],
    relatedIndustries: ["pressure-washing", "handyman", "pest-control"],
  },
  {
    slug: "pressure-washing",
    name: "Pressure washing",
    cluster: "home-services",
    oneLine: "Driveway, siding, and deck pressure-washing campaigns.",
    typicalOffer: "Whole-home wash special, driveway + siding bundle, free estimate.",
    routeMix: "Residential routes with driveways; older-home density.",
    timing: "Spring and early fall pushes.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "flyers"],
    relatedIndustries: ["landscaping", "cleaning-services", "handyman"],
  },
  {
    slug: "pool-service",
    name: "Pool service",
    cluster: "home-services",
    oneLine: "Pool opening, maintenance, and closing campaigns for pool businesses.",
    typicalOffer: "Pool opening special, weekly maintenance plan, free water test.",
    routeMix: "Residential routes with pool density.",
    timing: "Spring opening; fall closing.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "business-cards"],
    relatedIndustries: ["landscaping", "pressure-washing", "hvac"],
  },
  {
    slug: "locksmith",
    name: "Locksmith",
    cluster: "home-services",
    oneLine: "Residential and commercial locksmith campaigns.",
    typicalOffer: "Rekey special, new-homeowner package, 24/7 emergency.",
    routeMix: "Residential routes; new-homeowner dense areas.",
    timing: "Year-round with spring uptick.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "business-cards"],
    relatedIndustries: ["handyman", "garage-door", "electrical"],
  },
  {
    slug: "garage-door",
    name: "Garage door",
    cluster: "home-services",
    oneLine: "Repair, install, and maintenance campaigns for garage-door businesses.",
    typicalOffer: "Free inspection, spring tune-up, opener upgrade.",
    routeMix: "Residential routes with attached garages.",
    timing: "Spring and fall waves.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "business-cards"],
    relatedIndustries: ["hvac", "electrical", "handyman"],
  },
  {
    slug: "solar",
    name: "Solar",
    cluster: "home-services",
    oneLine: "Residential solar installation and consultation campaigns.",
    typicalOffer: "Free solar assessment, zero-down install, tax credit guide.",
    routeMix: "Residential routes with suitable roof orientation.",
    timing: "Year-round with state-incentive-driven pushes.",
    recommendedProducts: ["eddm-postcards", "oversized-postcards", "brochures"],
    relatedIndustries: ["roofing", "electrical", "remodeling"],
  },
  {
    slug: "handyman",
    name: "Handyman",
    cluster: "home-services",
    oneLine: "General-repair and small-project campaigns for handyman businesses.",
    typicalOffer: "Hourly rate special, first-service discount, project bundle.",
    routeMix: "Residential routes; older-home density.",
    timing: "Year-round with spring + fall pushes.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "business-cards"],
    relatedIndustries: ["cleaning-services", "painters", "electrical"],
  },
  {
    slug: "painters",
    name: "Painters",
    cluster: "home-services",
    oneLine: "Interior and exterior painting campaigns.",
    typicalOffer: "Free color consultation, exterior paint special, whole-room package.",
    routeMix: "Residential routes with single-family homes.",
    timing: "Exterior: spring and fall; interior: year-round.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "flyers"],
    relatedIndustries: ["remodeling", "handyman", "cleaning-services"],
  },
  {
    slug: "remodeling",
    name: "Remodeling",
    cluster: "home-services",
    oneLine: "Kitchen, bath, and whole-home remodeling campaigns.",
    typicalOffer: "Free design consultation, kitchen or bath package, financing option.",
    routeMix: "Residential routes with single-family homes, older homes.",
    timing: "Year-round with spring + fall emphasis.",
    recommendedProducts: ["oversized-postcards", "brochures", "rack-cards"],
    relatedIndustries: ["painters", "handyman", "roofing"],
  },
  // MEDICAL & WELLNESS
  {
    slug: "dental",
    name: "Dental",
    cluster: "medical-wellness",
    oneLine: "New-patient and specialty-procedure campaigns for dental practices.",
    typicalOffer: "New patient special, free consultation, whitening package.",
    routeMix: "Households within drive time; demographic overlays where useful.",
    timing: "Monthly cadence performs best.",
    recommendedProducts: ["eddm-postcards", "oversized-postcards", "rack-cards"],
    relatedIndustries: ["medical-practices", "chiropractic", "optometrists"],
  },
  {
    slug: "medical-practices",
    name: "Medical practices",
    cluster: "medical-wellness",
    oneLine: "New-patient and service-line campaigns for primary care, specialty, and clinics.",
    typicalOffer: "New patient special, annual wellness exam, procedure awareness.",
    routeMix: "Households within drive time; insurance coverage overlays.",
    timing: "Quarterly cadence with seasonal pushes.",
    recommendedProducts: ["eddm-postcards", "brochures", "rack-cards"],
    relatedIndustries: ["dental", "urgent-care", "chiropractic"],
  },
  {
    slug: "chiropractic",
    name: "Chiropractic",
    cluster: "medical-wellness",
    oneLine: "New-patient and wellness-program campaigns for chiropractic practices.",
    typicalOffer: "New patient special, free consultation, wellness plan.",
    routeMix: "Households within drive time; working-age density.",
    timing: "Monthly cadence works best.",
    recommendedProducts: ["eddm-postcards", "oversized-postcards", "rack-cards"],
    relatedIndustries: ["physical-therapy", "med-spa", "dental"],
  },
  {
    slug: "urgent-care",
    name: "Urgent care",
    cluster: "medical-wellness",
    oneLine: "Community-awareness and service-line campaigns for urgent care.",
    typicalOffer: "No appointment needed, insurance accepted, short wait times.",
    routeMix: "Households within drive time; family-heavy neighborhoods.",
    timing: "Year-round; flu-season push.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "rack-cards"],
    relatedIndustries: ["medical-practices", "pharmacies", "physical-therapy"],
  },
  {
    slug: "physical-therapy",
    name: "Physical therapy",
    cluster: "medical-wellness",
    oneLine: "New-patient and specialty-injury campaigns for physical therapy practices.",
    typicalOffer: "Free consultation, sports injury program, post-surgery recovery.",
    routeMix: "Households within drive time; active-demographic overlays.",
    timing: "Monthly cadence.",
    recommendedProducts: ["eddm-postcards", "brochures", "rack-cards"],
    relatedIndustries: ["chiropractic", "medical-practices", "gyms"],
  },
  {
    slug: "optometrists",
    name: "Optometrists",
    cluster: "medical-wellness",
    oneLine: "Eye-exam and eyewear campaigns for optometry practices.",
    typicalOffer: "Free eye exam with frames, back-to-school special, contact-lens promo.",
    routeMix: "Households within drive time; family and senior density.",
    timing: "Back-to-school and year-round.",
    recommendedProducts: ["eddm-postcards", "brochures", "rack-cards"],
    relatedIndustries: ["dental", "medical-practices", "pharmacies"],
  },
  {
    slug: "veterinarians",
    name: "Veterinarians",
    cluster: "medical-wellness",
    oneLine: "New-patient and wellness-program campaigns for veterinary practices.",
    typicalOffer: "New patient special, wellness plan, dental-month discount.",
    routeMix: "Residential routes; pet-owner density.",
    timing: "Monthly cadence with spring wellness push.",
    recommendedProducts: ["eddm-postcards", "rack-cards", "business-cards"],
    relatedIndustries: ["pet-grooming", "medical-practices", "dental"],
  },
  {
    slug: "pharmacies",
    name: "Pharmacies",
    cluster: "medical-wellness",
    oneLine: "Transfer-prescription and specialty-service campaigns for independent pharmacies.",
    typicalOffer: "Transfer your prescription, free delivery, immunization clinic.",
    routeMix: "Households within drive time; senior + family density.",
    timing: "Flu season and year-round.",
    recommendedProducts: ["eddm-postcards", "rack-cards", "brochures"],
    relatedIndustries: ["medical-practices", "urgent-care", "optometrists"],
  },
  {
    slug: "med-spa",
    name: "Med spa & wellness",
    cluster: "medical-wellness",
    oneLine: "Premium aesthetic and wellness campaigns for med spas.",
    typicalOffer: "Seasonal package, treatment series, intro offer for new services.",
    routeMix: "Targeted residential routes matching client demographic.",
    timing: "Monthly with creative rotation.",
    recommendedProducts: ["oversized-postcards", "brochures", "rack-cards"],
    relatedIndustries: ["spas", "nail-salons", "hair-salons"],
  },
  {
    slug: "spas",
    name: "Spas",
    cluster: "medical-wellness",
    oneLine: "Massage and wellness campaigns for day spas.",
    typicalOffer: "First-massage special, couples package, monthly membership.",
    routeMix: "Residential routes; mid-to-high income density.",
    timing: "Monthly; holiday gift push.",
    recommendedProducts: ["eddm-postcards", "rack-cards", "brochures"],
    relatedIndustries: ["med-spa", "hair-salons", "nail-salons"],
  },
  {
    slug: "hair-salons",
    name: "Hair salons",
    cluster: "medical-wellness",
    oneLine: "New-client and service-special campaigns for hair salons.",
    typicalOffer: "First-cut discount, color special, event-day updo.",
    routeMix: "Residential routes within walking or short drive time.",
    timing: "Monthly cadence.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "business-cards"],
    relatedIndustries: ["nail-salons", "spas", "med-spa"],
  },
  {
    slug: "nail-salons",
    name: "Nail salons",
    cluster: "medical-wellness",
    oneLine: "First-service and loyalty campaigns for nail salons.",
    typicalOffer: "First visit discount, mani-pedi bundle, loyalty card.",
    routeMix: "Residential routes within easy drive time.",
    timing: "Monthly cadence.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "business-cards"],
    relatedIndustries: ["hair-salons", "spas", "med-spa"],
  },
  // FOOD & HOSPITALITY
  {
    slug: "restaurants",
    name: "Restaurants",
    cluster: "food-hospitality",
    oneLine: "Grand opening, seasonal menu, and repeat-visit campaigns for restaurants.",
    typicalOffer: "Opening promo, seasonal menu, weekday deal, family bundle.",
    routeMix: "Residential routes within easy drive; foot-traffic corridors.",
    timing: "Pre-opening plus monthly cadence.",
    recommendedProducts: ["eddm-postcards", "brochures", "door-hangers"],
    relatedIndustries: ["cafes", "bars", "pizzerias"],
  },
  {
    slug: "cafes",
    name: "Cafes & coffee shops",
    cluster: "food-hospitality",
    oneLine: "Community-driven cafe campaigns with loyalty angles.",
    typicalOffer: "Buy-one-get-one, seasonal drink launch, loyalty card.",
    routeMix: "Residential routes + office-heavy neighborhoods.",
    timing: "Monthly cadence; seasonal drink pushes.",
    recommendedProducts: ["eddm-postcards", "rack-cards", "business-cards"],
    relatedIndustries: ["restaurants", "bars", "pizzerias"],
  },
  {
    slug: "bars",
    name: "Bars & breweries",
    cluster: "food-hospitality",
    oneLine: "Event-driven and loyalty campaigns for bars and breweries.",
    typicalOffer: "Event night promo, seasonal tap list, loyalty punch card.",
    routeMix: "Residential routes within walking or short drive.",
    timing: "Event-driven with monthly base.",
    recommendedProducts: ["eddm-postcards", "rack-cards", "flyers"],
    relatedIndustries: ["restaurants", "cafes", "pizzerias"],
  },
  {
    slug: "pizzerias",
    name: "Pizzerias",
    cluster: "food-hospitality",
    oneLine: "Delivery and event-special campaigns for pizza shops.",
    typicalOffer: "Delivery discount, family bundle, game-day special.",
    routeMix: "Residential routes within delivery radius.",
    timing: "Monthly; event-driven weekend pushes.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "flyers"],
    relatedIndustries: ["restaurants", "cafes", "bars"],
  },
  // FITNESS & EDUCATION
  {
    slug: "gyms",
    name: "Gyms",
    cluster: "fitness-education",
    oneLine: "Intro-membership and transformation campaigns for gyms.",
    typicalOffer: "Intro membership, 30-day transformation, class pack.",
    routeMix: "Residential routes; working-age density.",
    timing: "January kickoff; spring + fall refresh.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "rack-cards"],
    relatedIndustries: ["martial-arts", "physical-therapy", "med-spa"],
  },
  {
    slug: "martial-arts",
    name: "Martial arts",
    cluster: "fitness-education",
    oneLine: "Intro-class and family-program campaigns for martial arts schools.",
    typicalOffer: "Free intro class, family discount, summer camp.",
    routeMix: "Residential routes; family density.",
    timing: "Fall back-to-school + January.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "rack-cards"],
    relatedIndustries: ["gyms", "tutoring", "childcare"],
  },
  {
    slug: "music-lessons",
    name: "Music lessons",
    cluster: "fitness-education",
    oneLine: "Studio and private-lesson campaigns for music teachers.",
    typicalOffer: "Free intro lesson, sibling discount, summer program.",
    routeMix: "Residential routes; family density.",
    timing: "Back-to-school + spring.",
    recommendedProducts: ["eddm-postcards", "rack-cards", "business-cards"],
    relatedIndustries: ["tutoring", "private-schools", "childcare"],
  },
  {
    slug: "tutoring",
    name: "Tutoring",
    cluster: "fitness-education",
    oneLine: "Subject-specific and test-prep campaigns for tutoring services.",
    typicalOffer: "Free assessment, SAT/ACT prep, summer catch-up.",
    routeMix: "Residential routes; family density with school-age children.",
    timing: "Back-to-school + exam seasons.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "flyers"],
    relatedIndustries: ["music-lessons", "private-schools", "childcare"],
  },
  {
    slug: "private-schools",
    name: "Private schools",
    cluster: "fitness-education",
    oneLine: "Enrollment and open-house campaigns for private schools.",
    typicalOffer: "Open house event, application waiver, tuition assistance info.",
    routeMix: "Residential routes within commute radius; family density.",
    timing: "Fall + winter enrollment windows.",
    recommendedProducts: ["oversized-postcards", "brochures", "rack-cards"],
    relatedIndustries: ["tutoring", "childcare", "music-lessons"],
  },
  {
    slug: "childcare",
    name: "Childcare",
    cluster: "fitness-education",
    oneLine: "Enrollment and family-connection campaigns for childcare providers.",
    typicalOffer: "Tour and meet-the-teacher, enrollment special, sibling discount.",
    routeMix: "Residential routes; young-family density.",
    timing: "Summer + winter enrollment pushes.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "brochures"],
    relatedIndustries: ["private-schools", "music-lessons", "tutoring"],
  },
  // RETAIL, TRADE & PRO
  {
    slug: "auto-repair",
    name: "Auto repair",
    cluster: "retail-trade-pro",
    oneLine: "Service-package and preventive-maintenance campaigns for auto shops.",
    typicalOffer: "Oil change special, brake inspection, AC service.",
    routeMix: "Residential routes within drive time; vehicle-density areas.",
    timing: "Seasonal pushes (AC in summer, brakes in fall/winter).",
    recommendedProducts: ["eddm-postcards", "door-hangers", "business-cards"],
    relatedIndustries: ["auto-detailing", "tire-shops", "car-wash"],
  },
  {
    slug: "auto-detailing",
    name: "Auto detailing",
    cluster: "retail-trade-pro",
    oneLine: "Full-detail and membership campaigns for detailing shops.",
    typicalOffer: "First-detail discount, monthly membership, ceramic coating.",
    routeMix: "Residential routes; higher-income vehicle density.",
    timing: "Spring + pre-holiday pushes.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "rack-cards"],
    relatedIndustries: ["auto-repair", "car-wash", "tire-shops"],
  },
  {
    slug: "car-wash",
    name: "Car wash",
    cluster: "retail-trade-pro",
    oneLine: "Unlimited-wash and loyalty campaigns for car washes.",
    typicalOffer: "First wash free, unlimited monthly, loyalty card.",
    routeMix: "Residential routes within drive time; commuter corridors.",
    timing: "Year-round with spring push.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "flyers"],
    relatedIndustries: ["auto-detailing", "auto-repair", "tire-shops"],
  },
  {
    slug: "tire-shops",
    name: "Tire shops",
    cluster: "retail-trade-pro",
    oneLine: "Tire-replacement and seasonal-service campaigns for tire shops.",
    typicalOffer: "Buy-three-get-one, free alignment with install, winter tire bundle.",
    routeMix: "Residential routes within drive time; vehicle-density areas.",
    timing: "Spring + pre-winter pushes.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "business-cards"],
    relatedIndustries: ["auto-repair", "auto-detailing", "car-wash"],
  },
  {
    slug: "storage",
    name: "Self-storage",
    cluster: "retail-trade-pro",
    oneLine: "New-move-in campaigns for self-storage facilities.",
    typicalOffer: "First month free, second month half-off, no deposit.",
    routeMix: "Residential routes within drive time; rental-heavy areas.",
    timing: "Spring + summer move seasons.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "rack-cards"],
    relatedIndustries: ["moving-companies", "locksmith", "cleaning-services"],
  },
  {
    slug: "moving-companies",
    name: "Moving companies",
    cluster: "retail-trade-pro",
    oneLine: "Local and long-distance moving campaigns.",
    typicalOffer: "Free estimate, off-peak discount, packing bundle.",
    routeMix: "Residential routes within service area.",
    timing: "Spring + summer peak.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "rack-cards"],
    relatedIndustries: ["storage", "cleaning-services", "handyman"],
  },
  {
    slug: "florists",
    name: "Florists",
    cluster: "retail-trade-pro",
    oneLine: "Event and subscription campaigns for florists.",
    typicalOffer: "Weekly subscription, wedding package, event consult.",
    routeMix: "Residential routes within delivery range.",
    timing: "Valentine's + Mother's Day + holiday pushes.",
    recommendedProducts: ["eddm-postcards", "rack-cards", "business-cards"],
    relatedIndustries: ["restaurants", "spas", "private-schools"],
  },
  {
    slug: "dry-cleaners",
    name: "Dry cleaners",
    cluster: "retail-trade-pro",
    oneLine: "New-customer and loyalty campaigns for dry cleaners.",
    typicalOffer: "First-bag discount, pickup and delivery, monthly loyalty.",
    routeMix: "Residential routes within drive time; office-heavy neighborhoods.",
    timing: "Year-round with fall suit-season push.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "business-cards"],
    relatedIndustries: ["cleaning-services", "hair-salons", "nail-salons"],
  },
  {
    slug: "pet-grooming",
    name: "Pet grooming",
    cluster: "retail-trade-pro",
    oneLine: "First-groom and loyalty campaigns for pet groomers.",
    typicalOffer: "First groom special, monthly package, multi-pet discount.",
    routeMix: "Residential routes; pet-owner density.",
    timing: "Spring and summer pushes.",
    recommendedProducts: ["eddm-postcards", "door-hangers", "business-cards"],
    relatedIndustries: ["veterinarians", "hair-salons", "cleaning-services"],
  },
  // PROFESSIONAL & FINANCIAL
  {
    slug: "real-estate",
    name: "Real estate",
    cluster: "professional-financial",
    oneLine: "Neighborhood farming and just-listed campaigns for real estate.",
    typicalOffer: "Just-listed, just-sold, free home valuation, neighborhood market report.",
    routeMix: "Tightly-scoped farm-area routes.",
    timing: "Recurring monthly drops.",
    recommendedProducts: ["oversized-postcards", "eddm-postcards", "business-cards"],
    relatedIndustries: ["mortgage-brokers", "insurance", "remodeling"],
  },
  {
    slug: "mortgage-brokers",
    name: "Mortgage brokers",
    cluster: "professional-financial",
    oneLine: "Refinance and first-time-buyer campaigns for mortgage brokers.",
    typicalOffer: "Free rate quote, refinance calc, first-time-buyer guide.",
    routeMix: "Residential routes; mid-to-high income density.",
    timing: "Rate-change-driven; seasonal pushes.",
    recommendedProducts: ["eddm-postcards", "brochures", "rack-cards"],
    relatedIndustries: ["real-estate", "insurance", "accountants"],
  },
  {
    slug: "insurance",
    name: "Insurance",
    cluster: "professional-financial",
    oneLine: "Policy-review and bundle-savings campaigns for insurance agents.",
    typicalOffer: "Free policy review, bundle discount, new-home quote.",
    routeMix: "Residential routes; homeowner and auto-owner density.",
    timing: "Quarterly cadence.",
    recommendedProducts: ["eddm-postcards", "brochures", "rack-cards"],
    relatedIndustries: ["real-estate", "mortgage-brokers", "accountants"],
  },
  {
    slug: "legal",
    name: "Legal",
    cluster: "professional-financial",
    oneLine: "Practice-area and consultation campaigns for law firms.",
    typicalOffer: "Free consultation, will + estate package, specific practice-area offer.",
    routeMix: "Residential routes; practice-area demographic overlays.",
    timing: "Quarterly cadence with issue-driven pushes.",
    recommendedProducts: ["oversized-postcards", "brochures", "business-cards"],
    relatedIndustries: ["accountants", "insurance", "real-estate"],
  },
  {
    slug: "accountants",
    name: "Accountants",
    cluster: "professional-financial",
    oneLine: "Tax and small-business campaigns for accounting practices.",
    typicalOffer: "Free tax review, small-business bookkeeping, quarterly planning.",
    routeMix: "Residential routes; small-business density.",
    timing: "Tax season + quarterly.",
    recommendedProducts: ["eddm-postcards", "brochures", "business-cards"],
    relatedIndustries: ["legal", "insurance", "mortgage-brokers"],
  },
];

export const INDUSTRIES_BY_SLUG = Object.fromEntries(
  INDUSTRIES.map((i) => [i.slug, i] as const)
);

export function getIndustry(slug: string) {
  return INDUSTRIES_BY_SLUG[slug];
}

export function getIndustriesByCluster(clusterId: ClusterId): Industry[] {
  return INDUSTRIES.filter((i) => i.cluster === clusterId);
}

export const FEATURED_INDUSTRIES = [
  "home-services-featured", // placeholder — actual featured resolved by slug
];

/** Eight featured verticals for the hub page. */
export const FEATURED_INDUSTRY_SLUGS = [
  "hvac",
  "dental",
  "med-spa",
  "roofing",
  "real-estate",
  "restaurants",
  "gyms",
  "legal",
] as const;
